-- Schema matching DB2 CARDDEMO tables
CREATE SCHEMA IF NOT EXISTS CARDDEMO;

CREATE TABLE IF NOT EXISTS CARDDEMO.TRANSACTION_TYPE (
    TR_TYPE CHAR(2) NOT NULL,
    TR_DESCRIPTION VARCHAR(50) NOT NULL,
    PRIMARY KEY (TR_TYPE)
);

CREATE TABLE IF NOT EXISTS CARDDEMO.TRANSACTION_TYPE_CATEGORY (
    TRC_TYPE_CODE CHAR(2) NOT NULL,
    TRC_TYPE_CATEGORY CHAR(4) NOT NULL,
    TRC_CAT_DATA VARCHAR(50),
    PRIMARY KEY (TRC_TYPE_CODE, TRC_TYPE_CATEGORY),
    CONSTRAINT FK_TRC_TYPE FOREIGN KEY (TRC_TYPE_CODE)
        REFERENCES CARDDEMO.TRANSACTION_TYPE (TR_TYPE)
        ON DELETE RESTRICT
);
